// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIwiYPnOBNcG9O0X9mxw2yAd8F-sShPlA',
    appId: '1:65056178621:web:0b46432ef29a267a4152d4',
    messagingSenderId: '65056178621',
    projectId: 'agaram-milk',
    authDomain: 'agaram-milk.firebaseapp.com',
    storageBucket: 'agaram-milk.appspot.com',
    measurementId: 'G-DS1HB1BLFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2qwMHaiLFnABFSEbMfwyKCNPFnSohO8c',
    appId: '1:301303766507:android:0f9330cd89f35c21ea4dae',
    messagingSenderId: '301303766507',
    projectId: 'agaram-89794',
    databaseURL: 'https://agaram-89794-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agaram-89794.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBow-csijVonqM5EbNj_vLMsOCe0EDCNkk',
    appId: '1:65056178621:ios:41469bd1b689f4f54152d4',
    messagingSenderId: '65056178621',
    projectId: 'agaram-milk',
    storageBucket: 'agaram-milk.appspot.com',
    iosBundleId: 'com.example.agramMilkCompany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBow-csijVonqM5EbNj_vLMsOCe0EDCNkk',
    appId: '1:65056178621:ios:10e50979460849114152d4',
    messagingSenderId: '65056178621',
    projectId: 'agaram-milk',
    storageBucket: 'agaram-milk.appspot.com',
    iosBundleId: 'com.example.agramMilkCompany.RunnerTests',
  );
}